(()=>{'use strict';
const KEY='abyss_release_candidate_v1',T=54,W=21,H=21;
const THEMES=[{name:'地下洞窟',floor:'#3a2947',wall:'#20152a',accent:'#8a62ac'},{name:'灼熱火山',floor:'#5a2c25',wall:'#281314',accent:'#ef704c'},{name:'毒沼',floor:'#3c2947',wall:'#1b1322',accent:'#9bd653'},{name:'深淵ジャングル',floor:'#234233',wall:'#11231a',accent:'#68d59a'},{name:'氷結洞窟',floor:'#29465c',wall:'#12222e',accent:'#8ddcff'},{name:'雷神殿',floor:'#30375e',wall:'#15182d',accent:'#f4df68'}];
const BASE={
slime:{name:'スライム',color:'#42d66a',hp:46,atk:6,def:1,spd:10,crit:.08,skills:[{name:'粘液体当たり',type:'damage',power:1.3,status:'slow'},{name:'かばう',type:'cover'}]},
goblin:{name:'ゴブリン',color:'#918353',hp:52,atk:9,def:2,spd:15,crit:.16,skills:[{name:'二連斬り',type:'multi',power:.8,hits:2},{name:'急所突き',type:'damage',power:1.8,critBonus:.18}]},
fairy:{name:'妖精',color:'#7fe3f7',hp:34,atk:3,def:0,spd:18,crit:.05,skills:[{name:'単体回復',type:'heal',power:24},{name:'全体回復',type:'healAll',power:14}]},
dragon:{name:'ドラゴン',color:'#da5656',hp:130,atk:30,def:6,spd:5,crit:.2,skills:[{name:'火炎ブレス',type:'damage',power:2.2},{name:'竜爪撃',type:'damage',power:1.7,critBonus:.15}]},
mushroom:{name:'毒キノコ',color:'#b360c9',hp:58,atk:10,def:2,spd:7,crit:.08,skills:[{name:'毒胞子',type:'damage',power:1.2,status:'poison'},{name:'菌糸防御',type:'guard'}]},
wyvern:{name:'子ワイバーン',color:'#ca5e5e',hp:92,atk:20,def:4,spd:16,crit:.14,skills:[{name:'滑空撃',type:'damage',power:1.5},{name:'火球',type:'damage',power:1.8}]}};
const ENEMIES=[{id:'slime',name:'洞窟スライム',base:1,spd:9},{id:'goblin',name:'岩ゴブリン',base:1.18,spd:13},{id:'mushroom',name:'毒キノコ',base:1.28,spd:7},{id:'wyvern',name:'子ワイバーン',base:1.58,spd:16}];
const LOOT={weapon:['鉄の剣','骨の斧','魔晶の杖','炎竜の牙','深淵の大剣'],armor:['旅人の服','魔布のローブ','岩殻の鎧','氷晶の外套','竜鱗の鎧'],accessory:['疾風の指輪','幸運のお守り','悪魔の瞳','毒除けの首飾り','王者の冠']};
const DEFAULT={floor:1,maxFloor:1,checkpoint:1,nextShopFloor:4,gold:0,crystal:10,inRun:false,maxHp:160,hp:160,upgrades:{atk:0,hp:0,skill:0},souls:{},gear:[],inventory:{potion:5,capture:8},partyIds:['slime','goblin','fairy','dragon'],monsters:{slime:{id:'slime',name:'スライム',lv:1,exp:0,plus:0,equip:{weapon:null,armor:null,accessory:null}},goblin:{id:'goblin',name:'ゴブリン',lv:1,exp:0,plus:0,equip:{weapon:null,armor:null,accessory:null}},fairy:{id:'fairy',name:'妖精',lv:1,exp:0,plus:0,equip:{weapon:null,armor:null,accessory:null}},dragon:{id:'dragon',name:'ドラゴン',lv:1,exp:0,plus:0,equip:{weapon:null,armor:null,accessory:null}}}};
let state=load(),explore=null,battle=null,raf=0,last=0,homeTab='party',speed=1;
const $=id=>document.getElementById(id),cv=$('exploreCanvas'),cx=cv.getContext('2d'),screens=['homeScreen','exploreScreen','shopRoomScreen','battleScreen','resultScreen'];
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k])merge(a[k],b[k]);else a[k]=b[k]}return a}function load(){try{return merge(structuredClone(DEFAULT),JSON.parse(localStorage.getItem(KEY))||{})}catch{return structuredClone(DEFAULT)}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id))}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function dist(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}
function toast(t,ms=1100){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),ms)}function modal(h){$('modalBody').innerHTML=h;$('modal').classList.remove('hidden')}function theme(f=state.floor){return THEMES[Math.floor((f-1)/50)%THEMES.length]}function reqExp(lv){return Math.round(100*Math.pow(1.12,lv-1))}function plusNeed(p){return 5+Math.floor(p/10)*2}
function rarity(){const r=Math.random();return r<.01?'LR':r<.04?'SSR':r<.14?'SR':r<.4?'R':'N'}function rmul(r){return{N:1,R:1.35,SR:1.8,SSR:2.5,LR:3.5}[r]}
function eqBonus(m){const o={atk:0,hp:0,def:0,spd:0,crit:0};for(const slot of ['weapon','armor','accessory']){const g=state.gear.find(x=>String(x.uid)===String(m.equip[slot]));if(g){o.atk+=g.atk||0;o.hp+=g.hp||0;o.def+=g.def||0;o.spd+=g.spd||0;o.crit+=g.crit||0}}return o}
function memberData(id){const m=state.monsters[id],b=BASE[id]||BASE.slime,e=eqBonus(m),scale=1+(m.lv-1)*.055+m.plus*.018;return{id,name:m.name,lv:m.lv,exp:m.exp,plus:m.plus,color:b.color,maxHp:Math.round(b.hp*scale+e.hp),hp:Math.round(b.hp*scale+e.hp),atk:b.atk*scale+e.atk+state.upgrades.atk*1.4,def:b.def+e.def,spd:b.spd+e.spd,crit:b.crit+e.crit,skills:b.skills,guard:false,cover:false,alive:true,status:{},damage:0,healing:0}}
function party(){return state.partyIds.map(memberData)}
function dungeon(){const g=Array.from({length:H},()=>Array(W).fill(1));function carve(x,y){g[y][x]=0;for(const[dx,dy]of[[2,0],[-2,0],[0,2],[0,-2]].sort(()=>Math.random()-.5)){const nx=x+dx,ny=y+dy;if(nx>0&&ny>0&&nx<W-1&&ny<H-1&&g[ny][nx]){g[y+dy/2][x+dx/2]=0;carve(nx,ny)}}}carve(1,1);for(let i=0;i<24;i++){const x=1+Math.floor(Math.random()*(W-2)),y=1+Math.floor(Math.random()*(H-2));if(g[y][x]&&((!g[y][x-1]&&!g[y][x+1])||(!g[y-1][x]&&!g[y+1][x])))g[y][x]=0}return g}
function cells(g){const a=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++)if(!g[y][x])a.push({x,y});return a}function pick(a,f,m=8,ex=[]){const q=a.filter(x=>dist(x,f)>=m&&!ex.some(e=>e.x===x.x&&e.y===x.y));return structuredClone(q[Math.floor(Math.random()*q.length)]||a.at(-1))}
function bfs(g,a,z){const K=p=>p.x+','+p.y,q=[a],seen=new Set([K(a)]),pr=new Map(),ds=[[1,0],[-1,0],[0,1],[0,-1]];while(q.length){const c=q.shift();if(c.x===z.x&&c.y===z.y)break;for(const[dx,dy]of ds){const n={x:c.x+dx,y:c.y+dy},k=K(n);if(n.x<0||n.y<0||n.x>=W||n.y>=H||g[n.y][n.x]||seen.has(k))continue;seen.add(k);pr.set(k,c);q.push(n)}}const p=[];let c=z;while(c&&!(c.x===a.x&&c.y===a.y)){p.push(c);c=pr.get(K(c))}p.push(a);return p.reverse()}
function setup(){const g=dungeon(),a=cells(g),st={x:1,y:1},exit=pick(a,st,14),shop=state.floor>=state.nextShopFloor?pick(a,st,9,[exit]):null,ch1=pick(a,st,6,[exit,shop].filter(Boolean)),ch2=pick(a,st,5,[exit,shop,ch1].filter(Boolean));explore={g,a,p:{x:1,y:1,px:1,py:1,path:[],t:0},cam:{x:T,y:T,dragX:0,dragY:0},zoom:1,pointers:{},dragging:false,lastPoint:null,lastPinch:null,exit,shop,chests:[{...ch1,opened:false},{...ch2,opened:false}],enemies:[],pause:false,spawnTimer:12};for(let i=0;i<Math.min(10,4+Math.floor(state.floor/100));i++)spawn(true);show('exploreScreen');hud();last=performance.now();if(raf)cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);save()}
function spawn(force=false){const max=Math.min(10,4+Math.floor(state.floor/100));if(!force&&explore.enemies.filter(e=>e.alive).length>=max)return;const c=explore.a.filter(x=>dist(x,explore.p)>=7&&dist(x,explore.exit)>=3&&(!explore.shop||dist(x,explore.shop)>=3)&&!explore.enemies.some(e=>e.alive&&e.x===x.x&&e.y===x.y));if(!c.length)return;const p=structuredClone(c[Math.floor(Math.random()*c.length)]),type=ENEMIES[Math.min(ENEMIES.length-1,Math.floor(Math.random()*(1+Math.min(ENEMIES.length,state.floor/20+1))))],level=Math.max(1,state.floor+Math.floor(Math.random()*7)-2);explore.enemies.push({x:p.x,y:p.y,px:p.x,py:p.y,path:[],t:0,type,level,alive:true,patrol:1+Math.random()*2})}
function mover(o,dt,sp=4){if(!o.path.length)return false;const z=o.path[0];o.t+=dt*sp;o.px=o.x+(z.x-o.x)*Math.min(1,o.t);o.py=o.y+(z.y-o.y)*Math.min(1,o.t);if(o.t>=1){o.x=z.x;o.y=z.y;o.px=o.x;o.py=o.y;o.path.shift();o.t=0;return true}return false}
function hud(){$('floorHud').textContent=state.floor;$('goldHud').textContent=state.gold;$('crystalHud').textContent=state.crystal;$('armyHpText').textContent=Math.ceil(state.hp)+'/'+state.maxHp;$('armyHpBar').style.width=clamp(state.hp/state.maxHp*100,0,100)+'%'}
function update(dt){if(explore.pause)return;if(mover(explore.p,dt,4.8)){for(const c of explore.chests)if(!c.opened&&c.x===explore.p.x&&c.y===explore.p.y)openChest(c);for(const e of explore.enemies)if(e.alive&&e.x===explore.p.x&&e.y===explore.p.y)return startBattle(e);if(explore.shop&&explore.p.x===explore.shop.x&&explore.p.y===explore.shop.y)return enterShop();if(explore.p.x===explore.exit.x&&explore.p.y===explore.exit.y)return nextFloor()}for(const e of explore.enemies){if(!e.alive)continue;e.patrol-=dt;if(dist(e,explore.p)<=3)e.path=bfs(explore.g,e,explore.p).slice(1);else if(e.patrol<=0&&!e.path.length){const n=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>explore.g[p.y]&&!explore.g[p.y][p.x]);if(n.length)e.path=[n[Math.floor(Math.random()*n.length)]];e.patrol=1+Math.random()*2}if(mover(e,dt,2.1)&&e.x===explore.p.x&&e.y===explore.p.y)return startBattle(e)}explore.spawnTimer-=dt;if(explore.spawnTimer<=0){spawn();explore.spawnTimer=14+Math.random()*12}explore.cam.x+=(explore.p.px*T-explore.cam.x)*Math.min(1,dt*6);explore.cam.y+=(explore.p.py*T-explore.cam.y)*Math.min(1,dt*6);clampCam();hud();save()}
function clampCam(){const mw=W*T*explore.zoom,mh=H*T*explore.zoom;explore.cam.dragX=clamp(explore.cam.dragX,-Math.max(0,(mw-720)/2+T*2),Math.max(0,(mw-720)/2+T*2));explore.cam.dragY=clamp(explore.cam.dragY,-Math.max(0,(mh-980)/2+T*2),Math.max(0,(mh-980)/2+T*2))}
function draw(){const th=theme();cx.fillStyle='#09050d';cx.fillRect(0,0,720,980);cx.save();cx.translate(360-explore.cam.x*explore.zoom+explore.cam.dragX,490-explore.cam.y*explore.zoom+explore.cam.dragY);cx.scale(explore.zoom,explore.zoom);for(let y=0;y<H;y++)for(let x=0;x<W;x++){cx.fillStyle=explore.g[y][x]?th.wall:th.floor;cx.fillRect(x*T,y*T,T,T);if(!explore.g[y][x]){cx.strokeStyle='rgba(255,255,255,.045)';cx.strokeRect(x*T,y*T,T,T)}}cx.font='30px sans-serif';cx.fillText('🪜',explore.exit.x*T+12,explore.exit.y*T+38);if(explore.shop)cx.fillText('🚪',explore.shop.x*T+12,explore.shop.y*T+38);for(const c of explore.chests)if(!c.opened)cx.fillText('🎁',c.x*T+12,c.y*T+38);for(const e of explore.enemies)if(e.alive){cx.fillStyle=BASE[e.type.id]?.color||'#fff';cx.beginPath();cx.arc(e.px*T+T/2,e.py*T+T/2,15,0,Math.PI*2);cx.fill();cx.fillStyle='#fff';cx.font='10px sans-serif';cx.fillText(e.type.name,e.px*T-8,e.py*T+10);cx.fillText('Lv.'+e.level,e.px*T+8,e.py*T+22)}cx.fillStyle='#42d66a';cx.beginPath();cx.arc(explore.p.px*T+T/2,explore.p.py*T+T/2,17,0,Math.PI*2);cx.fill();cx.restore();mini(th)}
function mini(th){const ox=555,oy=18,q=7;cx.fillStyle='#0b0710dd';cx.fillRect(ox-8,oy-8,160,160);for(let y=0;y<H;y++)for(let x=0;x<W;x++){cx.fillStyle=explore.g[y][x]?th.wall:th.accent;cx.fillRect(ox+x*q,oy+y*q,q-1,q-1)}cx.fillStyle='#57ff8a';cx.fillRect(ox+explore.p.x*q+1,oy+explore.p.y*q+1,5,5);cx.fillStyle='#ff5252';cx.fillRect(ox+explore.exit.x*q+1,oy+explore.exit.y*q+1,5,5);if(explore.shop){cx.fillStyle='#ffd65e';cx.fillRect(ox+explore.shop.x*q+1,oy+explore.shop.y*q+1,5,5)}for(const c of explore.chests){cx.fillStyle=c.opened?'#777':'#fff071';cx.fillRect(ox+c.x*q+1,oy+c.y*q+1,5,5)}}
function loop(ts){const dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);draw();if(explore)raf=requestAnimationFrame(loop)}
function screenTile(x,y){const r=cv.getBoundingClientRect(),sx=(x-r.left)*(720/r.width),sy=(y-r.top)*(980/r.height);return{x:Math.floor((sx-360-explore.cam.dragX+explore.cam.x*explore.zoom)/(T*explore.zoom)),y:Math.floor((sy-490-explore.cam.dragY+explore.cam.y*explore.zoom)/(T*explore.zoom))}}
function openChest(c){c.opened=true;const r=Math.random();if(r<.22){const g=45+state.floor*4;state.gold+=g;toast('宝箱：'+g+'G')}else if(r<.36){state.inventory.potion++;toast('回復薬を獲得')}else if(r<.48){state.inventory.capture++;toast('捕獲結晶を獲得')}else if(r<.58){state.crystal++;toast('魔晶石を獲得')}else if(r<.68){const id=ENEMIES[Math.floor(Math.random()*ENEMIES.length)].id;state.souls[id]=(state.souls[id]||0)+1;toast(BASE[id].name+'の魔魂を獲得')}else{const g=randGear();state.gear.push(g);toast(g.rarity+' '+g.name+'を獲得')}save()}
function randGear(){const slots=['weapon','armor','accessory'],slot=slots[Math.floor(Math.random()*3)],r=rarity(),m=rmul(r),names=LOOT[slot],name=names[Math.floor(Math.random()*names.length)];return{uid:'g_'+Date.now()+'_'+Math.random(),name,slot,rarity:r,atk:slot==='weapon'?Math.round((5+state.floor*.3)*m):0,hp:slot==='armor'?Math.round((10+state.floor*.5)*m):0,def:slot==='armor'?Math.round((1+state.floor*.04)*m):0,spd:slot==='accessory'?Math.max(1,Math.round(2*m)):0,crit:slot==='accessory'?.01*m:0,sell:Math.round(35*m+state.floor)}}
function nextFloor(){state.floor++;state.maxFloor=Math.max(state.maxFloor,state.floor);if(state.floor%10===0){state.checkpoint=state.floor;toast('CHECKPOINT '+state.floor+'階')}if(state.floor%50===0)modal('<div class="eyebrow">NEW AREA</div><h2>'+theme().name+'</h2><p>景色と出現魔物が変化した。</p>');setup()}
function enterShop(){if(raf)cancelAnimationFrame(raf);state.nextShopFloor=state.floor+3+Math.floor(Math.random()*5);save();show('shopRoomScreen');$('shopRoomPanel').innerHTML='<h3>ここは安全地帯</h3><p class="muted">ベッドと商人を利用できる。</p>'}
function merchant(){$('shopRoomPanel').innerHTML='<div class="tabs"><button id="buyTab" class="active">購入</button><button id="sellTab">売却</button><button id="gearTab">装備</button><button id="backTab">戻る</button></div><div id="merchantContent"><div class="shopCard spread"><span>回復薬</span><button onclick="buyPotion()">50G</button></div><div class="shopCard spread"><span>捕獲結晶</span><button onclick="buyCapture()">80G</button></div><div class="shopCard spread"><span>ランダム装備</span><button onclick="buyGear()">160G</button></div></div>';$('sellTab').onclick=sellList;$('gearTab').onclick=gearList;$('backTab').onclick=()=>{$('shopRoomPanel').innerHTML='<h3>ここは安全地帯</h3><p class="muted">ベッドと商人を利用できる。</p>'}}
function gearSummary(g){return'ATK+'+(g.atk||0)+' HP+'+(g.hp||0)+' DEF+'+(g.def||0)+' SPD+'+(g.spd||0)+' CRIT+'+Math.round((g.crit||0)*100)+'%'}
function sellList(){$('merchantContent').innerHTML=state.gear.length?state.gear.map(g=>'<div class="shopCard spread"><div><b class="rarity-'+g.rarity+'">['+g.rarity+'] '+g.name+'</b><div class="small">売値 '+g.sell+'G</div></div><button onclick="sellGear(\''+g.uid+'\')">売る</button></div>').join(''):'売れる装備がない'}
function gearList(){$('merchantContent').innerHTML=state.gear.length?state.gear.map(g=>'<div class="shopCard spread"><div><b class="rarity-'+g.rarity+'">['+g.rarity+'] '+g.name+'</b><div class="small">'+gearSummary(g)+'</div></div><button onclick="chooseEquip(\''+g.uid+'\')">装備</button></div>').join(''):'装備がない'}
window.buyPotion=()=>{if(state.gold<50)return alert('G不足');state.gold-=50;state.inventory.potion++;merchant();save()};window.buyCapture=()=>{if(state.gold<80)return alert('G不足');state.gold-=80;state.inventory.capture++;merchant();save()};window.buyGear=()=>{if(state.gold<160)return alert('G不足');state.gold-=160;state.gear.push(randGear());merchant();save()};window.sellGear=uid=>{const i=state.gear.findIndex(g=>String(g.uid)===String(uid));if(i<0)return;const g=state.gear[i];for(const m of Object.values(state.monsters))for(const slot of ['weapon','armor','accessory'])if(String(m.equip[slot])===String(uid))m.equip[slot]=null;state.gold+=g.sell;state.gear.splice(i,1);sellList();save()};window.chooseEquip=uid=>{const g=state.gear.find(x=>String(x.uid)===String(uid));modal('<h3>'+g.name+'を誰に装備？</h3>'+state.partyIds.map(id=>'<button style="width:100%;margin:4px" onclick="equip(\''+id+'\',\''+uid+'\')">'+state.monsters[id].name+'</button>').join(''))};window.equip=(id,uid)=>{const g=state.gear.find(x=>String(x.uid)===String(uid));state.monsters[id].equip[g.slot]=g.uid;save();$('modal').classList.add('hidden');gearList()}
function enemyStats(f){const hp=Math.round((72+f.level*7)*f.type.base);return{id:f.type.id,name:f.type.name,color:BASE[f.type.id]?.color||'#fff',level:f.level,maxHp:hp,hp,atk:Math.round((5+f.level*.5)*f.type.base),def:Math.round(f.level*.08),spd:f.type.spd,status:{},guard:false}}
function startBattle(field){if(raf)cancelAnimationFrame(raf);explore.p.path=[];field.path=[];battle={field,enemy:enemyStats(field),party:party(),turn:1,auto:true,queue:[],idx:0,res:false};show('battleScreen');build();renderBattle();autoAct()}
function build(){battle.queue=[...battle.party.filter(x=>x.alive).map(x=>({side:'a',id:x.id,name:x.name,spd:x.spd-(x.status.slow?4:0)})),{side:'e',id:'e',name:battle.enemy.name,spd:battle.enemy.spd-(battle.enemy.status.slow?4:0)}].sort((a,b)=>b.spd-a.spd||Math.random()-.5);battle.idx=0}
function actor(){return battle.queue[battle.idx]}function member(){const a=actor();return a?.side==='a'?battle.party.find(x=>x.id===a.id):null}function chips(u){const a=[];if(u.guard)a.push('ガード');if(u.cover)a.push('かばう');if(u.status.slow)a.push('SPD↓');if(u.status.poison)a.push('毒 '+u.status.poison+'T');return a}
function renderBattle(){$('turnText').textContent=battle.turn;$('autoToggleBtn').textContent=battle.auto?'AUTO':'MANUAL';$('speedBtn').textContent='×'+speed.toFixed(1);$('turnOrder').innerHTML=battle.queue.slice(battle.idx).map((x,i)=>'<span class="orderToken '+(i===0?'current':'')+'">'+(i===0?'▶ ':'')+x.name+'</span>').join('');$('enemyName').textContent=battle.enemy.name+' Lv.'+battle.enemy.level;$('enemyMeta').textContent='ATK '+battle.enemy.atk+' / DEF '+battle.enemy.def+' / SPD '+battle.enemy.spd;$('enemyHpBar').style.width=clamp(battle.enemy.hp/battle.enemy.maxHp*100,0,100)+'%';$('enemyHpText').textContent=Math.ceil(Math.max(0,battle.enemy.hp))+'/'+battle.enemy.maxHp;$('enemyStatusChips').innerHTML=chips(battle.enemy).map(x=>'<span class="chip">'+x+'</span>').join('');$('enemySprite').style.color=battle.enemy.color;const a=actor();$('partyBattle').innerHTML=battle.party.map(m=>'<div class="member '+(a?.id===m.id?'active':'inactive')+' '+(!m.alive?'dead':'')+'"><div class="memberAvatar" data-avatar="'+m.id+'" style="background:'+m.color+'"></div><b>'+m.name+' Lv.'+m.lv+'+'+m.plus+'</b><div class="small">HP '+Math.ceil(Math.max(0,m.hp))+'/'+m.maxHp+'</div><div class="bar"><i style="width:'+clamp(m.hp/m.maxHp*100,0,100)+'%"></i></div><div class="small">ATK '+Math.round(m.atk)+' DEF '+m.def+' SPD '+m.spd+' CRIT '+Math.round(m.crit*100)+'%</div><div class="statusChips">'+chips(m).map(x=>'<span class="chip">'+x+'</span>').join('')+'</div></div>').join('');$('activeTurnName').textContent=(a?a.name:'')+'のターン';$('activeTurnHint').textContent=a?.side==='e'?'敵が行動中':battle.auto?'AUTOが選択中':'コマンドを選択';document.querySelectorAll('#mainCommands button').forEach(b=>b.disabled=battle.auto||battle.res||a?.side==='e');if(battle.auto||a?.side==='e')$('subCommands').innerHTML=''}
function autoAct(){clearTimeout(autoAct.t);const a=actor();if(!a)return;if(a.side==='e')autoAct.t=setTimeout(enemyAct,650/speed);else if(battle.auto)autoAct.t=setTimeout(()=>command(autoChoice(member())),650/speed)}function autoChoice(m){if(m.id==='fairy'){const low=[...battle.party].filter(x=>x.alive).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(low&&low.hp/low.maxHp<.48)return{kind:'skill',i:low.hp/low.maxHp<.22?1:0}}if(m.hp/m.maxHp<.18)return{kind:'guard'};return Math.random()<.48?{kind:'skill',i:Math.random()<.5?0:1}:{kind:'attack'}}
function msg(t){$('battleMessage').textContent=t}function fx(t,x,y,c){const e=document.createElement('div');e.className='fx '+c;e.textContent=t;e.style.left=x+'%';e.style.top=y+'%';$('effectLayer').appendChild(e);setTimeout(()=>e.remove(),850/speed)}function allyAnim(id){const a=document.querySelector('[data-avatar="'+id+'"]');if(a){a.classList.remove('attack');void a.offsetWidth;a.classList.add('attack')}}function enemyAnim(c){$('enemySprite').classList.remove('hit','attack');void $('enemySprite').offsetWidth;$('enemySprite').classList.add(c)}
function hit(m,p=1,bonus=0){allyAnim(m.id);const base=Math.max(1,Math.round((m.atk*p-battle.enemy.def)*(.88+Math.random()*.24))),crit=Math.random()<m.crit+bonus,dmg=crit?Math.round(base*1.8):base;battle.enemy.hp-=dmg;m.damage+=dmg;enemyAnim('hit');fx(crit?'CRIT '+dmg:'-'+dmg,72,28,crit?'crit':'dmg')}
function command(c){if(battle.res)return;const m=member();if(!m)return;battle.res=true;if(c.kind==='attack'){msg(m.name+'の通常攻撃！');hit(m)}if(c.kind==='guard'){m.guard=true;msg(m.name+'は身を守った');fx('GUARD',22,72,'guard')}if(c.kind==='item'){if(state.inventory.potion<=0){battle.res=false;return modal('<h3>回復薬がない</h3>')}state.inventory.potion--;m.hp=Math.min(m.maxHp,m.hp+40);msg(m.name+'は回復薬を使った');fx('+40',22,72,'heal')}if(c.kind==='capture'){capture();return}if(c.kind==='skill'){const sk=m.skills[c.i];msg(m.name+'の'+sk.name+'！');if(sk.type==='damage'){hit(m,sk.power,sk.critBonus||0);if(sk.status==='slow')battle.enemy.status.slow=true;if(sk.status==='poison')battle.enemy.status.poison=3}if(sk.type==='multi')for(let i=0;i<sk.hits;i++)hit(m,sk.power);if(sk.type==='heal'){const t=[...battle.party].filter(x=>x.alive).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];t.hp=Math.min(t.maxHp,t.hp+sk.power);m.healing+=sk.power;fx('+'+sk.power,22,72,'heal')}if(sk.type==='healAll'){for(const t of battle.party.filter(x=>x.alive)){t.hp=Math.min(t.maxHp,t.hp+sk.power);m.healing+=sk.power}fx('全体回復',22,72,'heal')}if(sk.type==='cover'){m.cover=true;fx('かばう',22,72,'guard')}if(sk.type==='guard'){m.guard=true;fx('GUARD',22,72,'guard')}}setTimeout(next,850/speed)}
function capture(){if(state.inventory.capture<=0){battle.res=false;return modal('<h3>捕獲結晶がない</h3>')}state.inventory.capture--;const best=Math.max(...battle.party.map(x=>x.lv)),ratio=battle.enemy.hp/battle.enemy.maxHp,ch=clamp(.48+(best-battle.enemy.level)*.025+(1-ratio)*.48,.03,.84);msg('捕獲を試みる… '+Math.round(ch*100)+'%');if(Math.random()<ch){addMonster(battle.enemy.id);fx('捕獲成功',50,44,'heal');setTimeout(victory,900/speed)}else{fx('捕獲失敗',50,44,'dmg');setTimeout(next,850/speed)}}
function enemyAct(){if(battle.res)return;battle.res=true;const a=battle.party.filter(x=>x.alive);if(!a.length)return gameOver();const t=a.find(x=>x.cover)||[...a].sort((x,y)=>x.hp-y.hp)[0];enemyAnim('attack');msg(battle.enemy.name+'の攻撃！');const dmg=Math.max(1,Math.round((battle.enemy.atk-t.def)*(t.guard?.5:1)));t.guard=false;t.hp-=dmg;fx('-'+dmg,22,72,'dmg');if(t.hp<=0){t.hp=0;t.alive=false}setTimeout(next,850/speed)}
function turnStatus(){if(battle.enemy.status.poison){const d=Math.max(1,Math.round(battle.enemy.maxHp*.04));battle.enemy.hp-=d;battle.enemy.status.poison--;fx('毒 '+d,72,28,'dmg');if(battle.enemy.status.poison<=0)delete battle.enemy.status.poison}for(const m of battle.party){m.guard=false;m.cover=false}}
function next(){battle.res=false;if(battle.enemy.hp<=0)return victory();if(!battle.party.some(x=>x.alive))return gameOver();battle.idx++;if(battle.idx>=battle.queue.length){turnStatus();battle.turn++;build()}renderBattle();autoAct()}
function grant(id,exp){const m=state.monsters[id],before=m.lv;m.exp+=exp;while(m.lv<999&&m.exp>=reqExp(m.lv)){m.exp-=reqExp(m.lv);m.lv++}if(m.lv===before)return null;const b=BASE[id],os=1+(before-1)*.055+m.plus*.018,ns=1+(m.lv-1)*.055+m.plus*.018;return{name:m.name,before,after:m.lv,hp:Math.round(b.hp*(ns-os)),atk:Math.max(1,Math.round(b.atk*(ns-os)))}}
function victory(){battle.field.alive=false;state.gold+=20;const exp=20+battle.enemy.level*5,ups=[];for(const m of battle.party){const r=grant(m.id,exp);if(r)ups.push(r)}if(Math.random()<.32)state.souls[battle.enemy.id]=(state.souls[battle.enemy.id]||0)+1;if(Math.random()<.1)state.gear.push(randGear());const n=battle.enemy.name;battle=null;show('exploreScreen');toast('勝利！ '+n+' / EXP '+exp);last=performance.now();raf=requestAnimationFrame(loop);save();if(ups.length)setTimeout(()=>modal('<div class="levelUpTitle">LEVEL UP!!</div>'+ups.map(x=>'<div class="levelMonster"><h3>'+x.name+' Lv.'+x.before+' → Lv.'+x.after+'</h3><p>HP +'+x.hp+'　ATK +'+x.atk+'</p></div>').join('')),450)}
function escape(){if(battle.res)return;const best=Math.max(...battle.party.filter(x=>x.alive).map(x=>x.spd)),ch=clamp(.55+(best-battle.enemy.spd)*.03,.15,.9);if(Math.random()<ch){battle=null;show('exploreScreen');toast('逃走成功');last=performance.now();raf=requestAnimationFrame(loop)}else{msg('逃走失敗！敵の攻撃！');fx('逃走失敗',50,44,'dmg');battle.queue=[{side:'e',id:'e',name:battle.enemy.name,spd:999},...battle.queue.slice(battle.idx)];battle.idx=0;renderBattle();autoAct()}}
function gameOver(){const lost=Math.floor(state.gold*.5);state.gold-=lost;state.floor=state.checkpoint;state.inRun=false;battle=null;result('GAME OVER','魔王軍全滅',['失ったG：'+lost,state.checkpoint+'階から再開可能'])}function result(e,t,a){$('resultEye').textContent=e;$('resultTitle').textContent=t;$('resultBody').innerHTML='<ul>'+a.map(x=>'<li>'+x+'</li>').join('')+'</ul>';show('resultScreen');save()}
function card(id,sel=false){const m=state.monsters[id],d=memberData(id);return'<div class="monsterCard '+(sel?'selected':'')+'"><div class="row"><div class="dot" style="background:'+d.color+'"></div><div><b>'+m.name+'</b><div class="small">Lv.'+m.lv+' +'+m.plus+'</div></div></div><div class="small">HP '+d.maxHp+' / ATK '+Math.round(d.atk)+' / DEF '+d.def+' / SPD '+d.spd+'</div><div class="bar"><i style="width:'+clamp(m.exp/reqExp(m.lv)*100,0,100)+'%"></i></div></div>'}
function home(){const th=theme(state.maxFloor);$('homeArea').textContent=th.name;$('homeProgress').textContent='最高到達 '+state.maxFloor+'階';$('homeResources').textContent='G '+state.gold+'　魔晶石 '+state.crystal+'　チェックポイント '+state.checkpoint+'階';$('startRunBtn').textContent=state.inRun?'探索を再開':'探索へ';document.querySelectorAll('#homeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===homeTab));if(homeTab==='party')$('homeContent').innerHTML='<div class="panel"><h3>編成中</h3><div class="homeGrid">'+state.partyIds.map(id=>card(id,true)).join('')+'</div></div>';if(homeTab==='monsters')$('homeContent').innerHTML='<div class="panel"><h3>所持モンスター</h3><div class="homeGrid">'+Object.keys(state.monsters).map(id=>'<div onclick="openMonster(\''+id+'\')">'+card(id,state.partyIds.includes(id))+'</div>').join('')+'</div></div>';if(homeTab==='gear')$('homeContent').innerHTML='<div class="panel"><h3>装備一覧</h3>'+(state.gear.length?state.gear.map(g=>'<div class="itemCard spread"><div><b class="rarity-'+g.rarity+'">['+g.rarity+'] '+g.name+'</b><div class="small">'+gearSummary(g)+'</div></div><button onclick="chooseEquip(\''+g.uid+'\')">装備</button></div>').join(''):'まだ装備なし')+'</div>';if(homeTab==='summon')$('homeContent').innerHTML='<div class="panel"><h3>召喚</h3><p>魔晶石：'+state.crystal+'</p><div class="row"><button class="primary" onclick="summonOne()">1回</button><button onclick="summonTen()">10連</button></div><h3>魔魂合成</h3>'+(Object.entries(state.souls).map(([id,n])=>'<div class="spread"><span>'+BASE[id].name+' ×'+n+'</span><button onclick="mergeSoul(\''+id+'\')">'+plusNeed(state.monsters[id]?.plus||0)+'個で+1</button></div>').join('')||'まだ魔魂なし')+'</div>';const fs=[];for(let f=1;f<=state.maxFloor;f+=10)fs.push(f);$('warpList').innerHTML=fs.map(f=>'<button data-warp="'+f+'">'+f+'階</button>').join('')}
window.openMonster=id=>{const m=state.monsters[id],d=memberData(id);modal('<h2>'+m.name+' Lv.'+m.lv+' +'+m.plus+'</h2><p>HP '+d.maxHp+'<br>ATK '+Math.round(d.atk)+'<br>DEF '+d.def+'<br>SPD '+d.spd+'<br>CRIT '+Math.round(d.crit*100)+'%</p><button onclick="toggleParty(\''+id+'\')">'+(state.partyIds.includes(id)?'編成から外す':'編成に入れる')+'</button>')};window.toggleParty=id=>{if(state.partyIds.includes(id)){if(state.partyIds.length<=1)return alert('最低1体必要');state.partyIds=state.partyIds.filter(x=>x!==id)}else{if(state.partyIds.length>=4)return alert('編成は4体まで');state.partyIds.push(id)}save();home();$('modal').classList.add('hidden')};function addMonster(id){if(state.monsters[id])state.monsters[id].plus++;else state.monsters[id]={id,name:BASE[id].name,lv:1,exp:0,plus:0,equip:{weapon:null,armor:null,accessory:null}}}
window.summonOne=()=>{if(state.crystal<1)return alert('魔晶石不足');state.crystal--;const ids=Object.keys(BASE),id=ids[Math.floor(Math.random()*ids.length)];addMonster(id);modal('<div class="levelUpTitle">SUMMON!</div><h2>'+BASE[id].name+' +1</h2>');save();home()};window.summonTen=()=>{if(state.crystal<10)return alert('魔晶石不足');state.crystal-=10;const ids=Object.keys(BASE),rs=[];for(let i=0;i<10;i++){const id=ids[Math.floor(Math.random()*ids.length)];addMonster(id);rs.push(BASE[id].name)}modal('<div class="levelUpTitle">10連召喚</div><p>'+rs.join(' / ')+'</p>');save();home()};window.mergeSoul=id=>{const n=plusNeed(state.monsters[id]?.plus||0);if((state.souls[id]||0)<n)return alert('魔魂が'+n+'個必要');state.souls[id]-=n;addMonster(id);save();home()}
function openPage(p){if(p==='status')sheet('<h3>ステータス</h3>'+state.partyIds.map(id=>card(id)).join(''));if(p==='merge')sheet('<h3>魔魂合成</h3>'+(Object.entries(state.souls).map(([id,n])=>'<div class="spread"><span>'+BASE[id].name+' ×'+n+'</span><button onclick="mergeSoul(\''+id+'\')">合成</button></div>').join('')||'魔魂なし'));if(p==='gear')sheet('<h3>装備一覧</h3>'+(state.gear.length?state.gear.map(g=>'<div class="small">['+g.rarity+'] '+g.name+' '+gearSummary(g)+'</div>').join(''):'なし'));if(p==='shop')sheet('<h3>ショップ案内</h3><p>ダンジョン内の🚪から安全地帯へ入れる。</p>')}function sheet(h){$('sheetBody').innerHTML=h;$('sheet').classList.remove('hidden')}
cv.addEventListener('pointerdown',e=>{if(!explore)return;cv.setPointerCapture(e.pointerId);explore.pointers[e.pointerId]={x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY};if(Object.keys(explore.pointers).length===1){explore.dragging=false;explore.lastPoint={x:e.clientX,y:e.clientY}}});cv.addEventListener('pointermove',e=>{if(!explore?.pointers[e.pointerId])return;explore.pointers[e.pointerId].x=e.clientX;explore.pointers[e.pointerId].y=e.clientY;const ps=Object.values(explore.pointers);if(ps.length===1){const dx=e.clientX-explore.lastPoint.x,dy=e.clientY-explore.lastPoint.y;if(Math.hypot(e.clientX-ps[0].sx,e.clientY-ps[0].sy)>8)explore.dragging=true;if(explore.dragging){explore.cam.dragX+=dx;explore.cam.dragY+=dy;explore.lastPoint={x:e.clientX,y:e.clientY};clampCam()}}else if(ps.length===2){const d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);if(explore.lastPinch)explore.zoom=clamp(explore.zoom*d/explore.lastPinch,.45,1.4);explore.lastPinch=d;clampCam()}});cv.addEventListener('pointerup',e=>{if(!explore)return;const p=explore.pointers[e.pointerId];delete explore.pointers[e.pointerId];if(Object.keys(explore.pointers).length<2)explore.lastPinch=null;if(!explore.dragging&&p){const t=screenTile(e.clientX,e.clientY);if(t.x<0||t.y<0||t.x>=W||t.y>=H)return;if(!explore.g[t.y][t.x])explore.p.path=bfs(explore.g,explore.p,t).slice(1)}})
$('startRunBtn').onclick=()=>{state.inRun=true;state.floor=Math.max(1,state.floor||state.checkpoint);state.maxHp=160+state.upgrades.hp*20;if(!state.hp||state.hp<=0)state.hp=state.maxHp;setup()};$('returnBtn').onclick=()=>{if(confirm('帰還する？')){state.inRun=false;save();result('RETURN','帰還',['到達階：'+state.floor])}};$('resultHomeBtn').onclick=()=>{home();show('homeScreen')};$('sheetClose').onclick=()=>$('sheet').classList.add('hidden');$('modalCloseBtn').onclick=()=>$('modal').classList.add('hidden');$('homeTabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){homeTab=b.dataset.tab;home()}};$('warpList').onclick=e=>{const b=e.target.closest('[data-warp]');if(b){state.floor=+b.dataset.warp;state.checkpoint=state.floor;state.inRun=true;setup()}};document.querySelector('.exploreNav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)openPage(b.dataset.page)};$('leaveShopBtn').onclick=()=>{show('exploreScreen');last=performance.now();raf=requestAnimationFrame(loop)};document.querySelector('.roomScene').onclick=e=>{const c=e.target.closest('[data-room]');if(!c)return;if(c.dataset.room==='bed'){if(state.gold<100)return $('shopRoomPanel').innerHTML='<h3>G不足</h3><p>100G必要。</p>';state.gold-=100;state.hp=state.maxHp;$('shopRoomPanel').innerHTML='<h3>全回復した！</h3>'}else merchant();save()};$('autoToggleBtn').onclick=()=>{battle.auto=!battle.auto;clearTimeout(autoAct.t);renderBattle();if(battle.auto)autoAct()};$('speedBtn').onclick=()=>{speed=speed===.5?1:speed===1?1.5:speed===1.5?2:.5;renderBattle()};$('escapeBtn').onclick=escape;$('mainCommands').onclick=e=>{const b=e.target.closest('[data-command]');if(!b||battle.auto||battle.res)return;const c=b.dataset.command;if(c==='attack')command({kind:'attack'});if(c==='guard')command({kind:'guard'});if(c==='item')command({kind:'item'});if(c==='capture')command({kind:'capture'});if(c==='skills')$('subCommands').innerHTML=member().skills.map((s,i)=>'<button data-skill="'+i+'">'+s.name+'</button>').join('')};$('subCommands').onclick=e=>{const b=e.target.closest('[data-skill]');if(b&&!battle.auto&&!battle.res)command({kind:'skill',i:+b.dataset.skill})};$('exportSaveBtn').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state));modal('<h3>セーブデータをコピーした</h3>')}catch{modal('<textarea style="width:100%;height:180px">'+JSON.stringify(state)+'</textarea>')}};$('resetSaveBtn').onclick=()=>{if(confirm('本当に初期化する？')){localStorage.removeItem(KEY);location.reload()}};
home();if(state.inRun)setup();else show('homeScreen');
})();
