"use strict";
const GRID=8,CELLS=64,WAVES=5,SAVE_KEY="dungeonManagerV3";
const rarityRank={N:1,R:2,SR:3,SSR:4,UR:5};
const tribeData={
 slime:{name:"スライム族",icon:"🟢",rarity:"N",hp:18,atk:4,speed:1.0,role:"壁役",skill:"分裂",unitCost:50,evolutions:["キングスライム族","毒スライム族","メタルスライム族"]},
 goblin:{name:"ゴブリン族",icon:"👺",rarity:"R",hp:16,atk:7,speed:1.1,role:"集団戦",skill:"群れの力",unitCost:120,evolutions:["ホブゴブリン族","暗殺ゴブリン族"]},
 wolf:{name:"魔狼族",icon:"🐺",rarity:"SR",hp:22,atk:9,speed:1.35,role:"先制攻撃",skill:"追撃",unitCost:260,evolutions:["フェンリル族","影狼族"]},
 undead:{name:"アンデッド族",icon:"💀",rarity:"SR",hp:28,atk:7,speed:.8,role:"復活",skill:"不死",unitCost:300,evolutions:["リッチ族","デスナイト族"]},
 dragon:{name:"ドラゴン族",icon:"🐉",rarity:"SSR",hp:55,atk:16,speed:.7,role:"範囲火力",skill:"炎ブレス",unitCost:1200,evolutions:["古龍族","骨龍族"]}
};
const equipmentData={
 rustySword:{name:"錆びた短剣",icon:"🗡️",rarity:"N",atk:2,set:"勇者殺し"},
 ironSword:{name:"鉄の剣",icon:"⚔️",rarity:"R",atk:5,set:"勇者殺し"},
 woodShield:{name:"木の盾",icon:"🛡️",rarity:"N",hp:5,set:"守護者"},
 magicStone:{name:"魔力石",icon:"🔮",rarity:"SR",atk:4,hp:8,set:"魔導"},
 dragonFang:{name:"竜牙",icon:"🦷",rarity:"SSR",atk:11,set:"竜装"}
};
const freshState=()=>({version:3,gold:500,gems:3,stage:1,wave:1,boss:{hp:100,maxHp:100},tribes:{slime:{unlocked:true,duplicates:1,rank:0,pity:0,proficiency:1,xp:0,units:5,injured:0,evolution:null,equipment:null,kills:0,deaths:0}},equipment:{rustySword:1},gacha:{dailyDate:"",normalPity:0,premiumPity:0,history:[]},map:{entrance:0,goal:63,rocks:[]},placed:[],heroMemory:{battles:0,slimeDeaths:0,bossReached:0,blockedRoutes:0,lastDeathCell:null},records:{stageClears:0,gachaPulls:0,fusions:0,fusionFails:0,equipmentDrops:0}});
let S=freshState(),battle=false,hero=null,monsterStates={},route=[],selectedTribe="slime",pointerActive=false,pointerMode="place",visited=new Set(),toastTimer,autoSaveTimer;
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms)),clone=o=>JSON.parse(JSON.stringify(o)),rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a,choice=a=>a[Math.floor(Math.random()*a.length)],today=()=>new Date().toISOString().slice(0,10);
const dom={title:$('titleScreen'),game:$('gameScreen'),newGame:$('newGameButton'),cont:$('continueButton'),grid:$('dungeonGrid'),gold:$('goldText'),gems:$('gemText'),stage:$('stageText'),wave:$('waveText'),bossText:$('bossHpText'),bossFill:$('bossHpFill'),bossMsg:$('bossMessage'),titleText:$('dungeonTitle'),hand:$('handList'),battleBtn:$('battleButton'),battleLog:$('battleLog'),clear:$('clearButton'),placeMode:$('placementMode'),routeInfo:$('routeInfo'),dailyBtn:$('dailyGachaButton'),normalBtn:$('normalGachaButton'),premiumBtn:$('premiumGachaButton'),dailyBadge:$('dailyBadge'),normalRates:$('normalRates'),premiumRates:$('premiumRates'),normalPity:$('normalPity'),premiumPity:$('premiumPity'),history:$('gachaHistory'),enhance:$('enhanceList'),status:$('statusList'),equipInv:$('equipmentInventory'),codex:$('codexContent'),menu:$('menuModal'),result:$('resultModal'),resultIcon:$('resultIcon'),resultTitle:$('resultTitle'),resultBody:$('resultBody'),toast:$('toast')};
function showToast(t){dom.toast.textContent=t;dom.toast.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>dom.toast.classList.add('hidden'),1800)}
function persistGame({silent=true}={}){if(battle)return false;try{localStorage.setItem(SAVE_KEY,JSON.stringify(S));dom.cont.classList.remove('hidden');if(!silent)showToast('セーブした！');return true}catch(error){console.error(error);if(!silent)showToast('セーブに失敗した');return false}}
function scheduleAutoSave(){if(battle)return;clearTimeout(autoSaveTimer);autoSaveTimer=setTimeout(()=>persistGame(),350)}
function restoreGame({showGame=true}={}){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;try{const data=JSON.parse(raw);if(!data||data.version!==3)throw new Error('save version mismatch');S=data;route=pathfind(S.map.entrance,S.map.goal,S.map.rocks)||[];if(showGame){dom.title.classList.add('hidden');dom.game.classList.remove('hidden')}renderAll();return true}catch(error){console.error(error);showToast('セーブデータを読み込めなかった');return false}}
function showResult(icon,title,body){dom.resultIcon.textContent=icon;dom.resultTitle.textContent=title;dom.resultBody.innerHTML=body;dom.result.classList.remove('hidden')}
function edgeCells(edge){return Array.from({length:GRID},(_,i)=>edge==='top'?i:edge==='bottom'?(GRID-1)*GRID+i:edge==='left'?i*GRID:i*GRID+GRID-1)}
function neighbors(i){const r=Math.floor(i/GRID),c=i%GRID;return [[r-1,c],[r+1,c],[r,c-1],[r,c+1]].filter(([y,x])=>y>=0&&y<GRID&&x>=0&&x<GRID).map(([y,x])=>y*GRID+x)}
function pathfind(start,goal,blocked=[]){const block=new Set(blocked),q=[start],prev=new Map(),seen=new Set([start]);while(q.length){const cur=q.shift();if(cur===goal)break;for(const n of neighbors(cur).sort(()=>Math.random()-.5)){if(seen.has(n)||(block.has(n)&&n!==goal))continue;seen.add(n);prev.set(n,cur);q.push(n)}}if(!seen.has(goal))return null;const p=[];for(let x=goal;x!==undefined;x=prev.get(x)){p.unshift(x);if(x===start)break}return p}
function generateMap(){const edges=['top','right','bottom','left'],e=choice(edges),opp={top:'bottom',bottom:'top',left:'right',right:'left'}[e];S.map.entrance=choice(edgeCells(e));S.map.goal=choice(edgeCells(opp));const rocks=[],candidates=Array.from({length:CELLS},(_,i)=>i).filter(i=>i!==S.map.entrance&&i!==S.map.goal).sort(()=>Math.random()-.5);for(const c of candidates){if(rocks.length>=rand(7,12))break;const test=[...rocks,c];if(pathfind(S.map.entrance,S.map.goal,test))rocks.push(c)}S.map.rocks=rocks;S.placed.forEach(p=>{if(S.tribes[p.tribe])S.tribes[p.tribe].units++});S.placed=[];route=pathfind(S.map.entrance,S.map.goal,S.map.rocks)||[]}
function tribeStats(id){const d=tribeData[id],t=S.tribes[id],rank=t?.rank||0,prof=t?.proficiency||1;let hp=Math.round(d.hp*(1+rank*.12+prof*.015)),atk=Math.round(d.atk*(1+rank*.1+prof*.012));const eq=t?.equipment?equipmentData[t.equipment]:null;if(eq){hp+=eq.hp||0;atk+=eq.atk||0}if(id==='goblin'&&S.placed.filter(p=>p.tribe==='goblin').length>=2)atk=Math.round(atk*1.15);return{hp,atk,speed:d.speed}}
function newStage(){S.wave=1;S.boss.maxHp=100+(S.stage-1)*20;S.boss.hp=S.boss.maxHp;generateMap();renderAll();dom.battleLog.textContent=`STAGE ${S.stage}開始。入口・岩・魔王位置が変化した。`}
function createGrid(){dom.grid.innerHTML='';for(let i=0;i<CELLS;i++){const cell=document.createElement('div');cell.className='dungeon-cell';cell.dataset.i=i;cell.addEventListener('pointerdown',e=>pointerDown(e,i));cell.addEventListener('pointerenter',e=>pointerEnter(e,i));dom.grid.appendChild(cell)}renderGrid()}
function renderGrid(){const cells=[...dom.grid.children];cells.forEach((cell,i)=>{cell.className='dungeon-cell';cell.innerHTML='';if(route.includes(i))cell.classList.add('route');if(S.map.rocks.includes(i)){cell.classList.add('rock');cell.textContent='🪨';return}if(i===S.map.entrance){cell.classList.add('entrance');cell.textContent='🚪'}if(i===S.map.goal){cell.classList.add('goal');cell.textContent='👑'}});S.placed.forEach(p=>{const c=cells[p.cell],st=monsterStates[p.id],d=tribeData[p.tribe];if(!c)return;c.classList.add('occupied');const hp=st?.hp??tribeStats(p.tribe).hp,max=st?.max??tribeStats(p.tribe).hp;c.innerHTML+=`<span class="cell-unit">${st?.dead?'💫':d.icon}</span>${battle?`<div class="unit-hp"><div style="width:${Math.max(0,hp/max*100)}%"></div></div>`:''}`});if(hero){const c=cells[hero.cell];if(c){const el=document.createElement('div');el.className='hero-unit';el.innerHTML=`<span>🧑‍⚔️</span><div class="unit-hp"><div style="width:${Math.max(0,hero.hp/hero.maxHp*100)}%"></div></div>`;c.appendChild(el)}}}
function pointerDown(e,i){e.preventDefault();if(battle)return showToast('戦闘中は変更できない');pointerActive=true;visited=new Set();pointerMode=S.placed.some(p=>p.cell===i)?'erase':'place';dom.placeMode.textContent=pointerMode==='erase'?'撤去モード':'連続配置中';processCell(i)}
function pointerEnter(e,i){if(pointerActive){e.preventDefault();processCell(i)}}
function processCell(i){if(visited.has(i))return;visited.add(i);pointerMode==='erase'?removeAt(i):placeAt(i)}
function pointerEnd(){pointerActive=false;visited.clear();dom.placeMode.textContent='配置モード'}
function placeAt(i){if([S.map.entrance,S.map.goal].includes(i)||S.map.rocks.includes(i)||S.placed.some(p=>p.cell===i))return;const t=S.tribes[selectedTribe];if(!t||t.units<=0)return;t.units--;S.placed.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,tribe:selectedTribe,cell:i});renderAll()}
function removeAt(i){const idx=S.placed.findIndex(p=>p.cell===i);if(idx<0)return;const [p]=S.placed.splice(idx,1);S.tribes[p.tribe].units++;renderAll()}
function clearPlaced(){if(battle)return;S.placed.forEach(p=>S.tribes[p.tribe].units++);S.placed=[];renderAll()}
function renderHand(){dom.hand.innerHTML='';Object.entries(S.tribes).filter(([,t])=>t.unlocked).forEach(([id,t])=>{const d=tribeData[id],s=tribeStats(id),b=document.createElement('button');b.className=`hand-card ${selectedTribe===id?'selected':''}`;b.innerHTML=`<span class="hand-icon">${d.icon}</span><span><b>${d.name}＋${t.rank}</b><small> HP ${s.hp} / ATK ${s.atk} / ${d.role}</small></span><strong>×${t.units}</strong>`;b.onclick=()=>{selectedTribe=id;renderHand()};dom.hand.appendChild(b)})}
function fusionChance(id){const t=S.tribes[id],base={N:100,R:90,SR:75,SSR:55,UR:35}[tribeData[id].rarity];return Math.max(10,base-t.rank*8+t.pity*5)}
function renderEnhance(){dom.enhance.innerHTML='';Object.entries(S.tribes).filter(([,t])=>t.unlocked).forEach(([id,t])=>{const d=tribeData[id],chance=fusionChance(id),need=1;const card=document.createElement('article');card.className='tribe-card';card.innerHTML=`<header><span class="tribe-icon">${d.icon}</span><div><h4>${d.name}＋${t.rank}</h4><small>${d.rarity}・重複素材 ${t.duplicates}</small></div></header><div class="tribe-meta"><span class="tag">成功率 ${chance}%</span><span class="tag">失敗補正 +${t.pity*5}%</span><span class="tag">熟練Lv.${t.proficiency}</span></div><p class="hint">失敗時は素材だけ消滅。失敗するほど次回成功率が上がる。</p><button class="action-btn" ${t.duplicates<need?'disabled':''}>同部族を合成する</button>`;card.querySelector('button').onclick=()=>fuseTribe(id);dom.enhance.appendChild(card)})}
function fuseTribe(id){const t=S.tribes[id];if(t.duplicates<1)return;t.duplicates--;S.records.fusions++;const chance=fusionChance(id),success=Math.random()*100<chance;if(success){t.rank++;t.pity=0;showResult('✨','合成成功！',`${tribeData[id].name}が<strong>＋${t.rank}</strong>になった！`)}else{t.pity++;S.records.fusionFails++;showResult('💥','合成失敗',`素材は消滅した。次回成功率が<strong>＋5%</strong>上昇。`)}renderAll()}
function renderStatus(){dom.status.innerHTML='';Object.entries(S.tribes).filter(([,t])=>t.unlocked).forEach(([id,t])=>{const d=tribeData[id],s=tribeStats(id);const options=['<option value="">装備なし</option>',...Object.entries(S.equipment).filter(([,n])=>n>0).map(([eid,n])=>`<option value="${eid}" ${t.equipment===eid?'selected':''}>${equipmentData[eid].name} ×${n}</option>`)].join('');const card=document.createElement('article');card.className='tribe-card';card.innerHTML=`<header><span class="tribe-icon">${d.icon}</span><div><h4>${d.name}＋${t.rank}</h4><small>${d.rarity} / ${d.role} / ${d.skill}</small></div></header><div class="stats"><div class="stat-box"><small>HP</small><b>${s.hp}</b></div><div class="stat-box"><small>ATK</small><b>${s.atk}</b></div><div class="stat-box"><small>個体</small><b>${t.units}</b></div></div><div class="tribe-meta"><span class="tag">熟練 Lv.${t.proficiency}</span><span class="tag">撃破 ${t.kills}</span><span class="tag">死亡 ${t.deaths}</span><span class="tag">負傷 ${t.injured}</span></div><div class="equip-row"><select class="select">${options}</select><button class="action-btn">装備</button></div><p class="hint">進化候補：${d.evolutions.join(' / ')}</p>`;const sel=card.querySelector('select');card.querySelector('button').onclick=()=>{t.equipment=sel.value||null;showToast('部族装備を変更した');renderAll()};dom.status.appendChild(card)});dom.equipInv.innerHTML='';Object.entries(S.equipment).forEach(([id,n])=>{if(n<=0)return;const e=equipmentData[id];dom.equipInv.innerHTML+=`<div class="equipment-card"><b>${e.icon} ${e.name}</b><small>${e.rarity} / ${e.atk?`ATK＋${e.atk}`:''} ${e.hp?`HP＋${e.hp}`:''} / セット：${e.set}</small><strong>×${n}</strong></div>`})}
function renderCodex(){const unlocked=Object.keys(S.tribes).length,total=Object.keys(tribeData).length;dom.codex.innerHTML=`<div class="stats"><div class="stat-box"><small>部族図鑑</small><b>${unlocked}/${total}</b></div><div class="stat-box"><small>最高STAGE</small><b>${S.stage}</b></div><div class="stat-box"><small>ガチャ</small><b>${S.records.gachaPulls}</b></div></div><div class="history-list" style="margin-top:10px"><div class="history-item">🏆 ステージ突破：${S.records.stageClears}</div><div class="history-item">✨ 合成回数：${S.records.fusions}</div><div class="history-item">💥 合成失敗：${S.records.fusionFails}</div><div class="history-item">🎁 装備ドロップ：${S.records.equipmentDrops}</div><div class="history-item">🧠 勇者学習値：${S.heroMemory.battles+S.heroMemory.bossReached+S.heroMemory.slimeDeaths}</div></div>`}
function currentRates(type){if(type==='normal'){if(S.stage<5)return{N:80,R:18,SR:2};if(S.stage<10)return{N:65,R:30,SR:5};return{N:50,R:38,SR:11,SSR:1}}if(S.stage<10)return{R:65,SR:30,SSR:5};return{R:45,SR:42,SSR:12,UR:1}}
function rollRarity(rates,forced=null){if(forced)return forced;let r=Math.random()*100,sum=0;for(const [k,v] of Object.entries(rates)){sum+=v;if(r<sum)return k}return Object.keys(rates).at(-1)}
function availableTribes(rarity){return Object.entries(tribeData).filter(([,d])=>d.rarity===rarity&&rarityRank[d.rarity]<=Math.min(5,1+Math.floor((S.stage-1)/4)+1)).map(([id])=>id)}
function doGacha(type){if(type==='daily'&&S.gacha.dailyDate===today())return showToast('今日はもう引いてるよ');if(type==='normal'&&S.gold<300)return showToast('ゴールド不足');if(type==='premium'&&S.gems<3)return showToast('魔晶石不足');if(type==='normal')S.gold-=300;if(type==='premium')S.gems-=3;if(type==='daily')S.gacha.dailyDate=today();S.records.gachaPulls++;const pityKey=type==='premium'?'premiumPity':'normalPity';if(type!=='daily')S.gacha[pityKey]++;let forced=null;if(type==='normal'&&S.gacha.normalPity>=50){forced='R';S.gacha.normalPity=0}if(type==='premium'&&S.gacha.premiumPity>=30){forced='SR';S.gacha.premiumPity=0}const rates=type==='premium'?currentRates('premium'):currentRates('normal'),rarity=rollRarity(rates,forced);const pool=availableTribes(rarity);const category=Math.random();let result;if(pool.length&&category<.62){const id=choice(pool),d=tribeData[id];if(!S.tribes[id]){S.tribes[id]={unlocked:true,duplicates:0,rank:0,pity:0,proficiency:1,xp:0,units:1,injured:0,evolution:null,equipment:null,kills:0,deaths:0};result={icon:d.icon,title:'新部族解禁！',body:`${d.name}を解禁。個体を1体獲得した。`}}else{S.tribes[id].duplicates++;result={icon:d.icon,title:'部族重複！',body:`${d.name}の合成素材を1個獲得。`}}}else if(category<.82){const unlocked=Object.keys(S.tribes),id=choice(unlocked);S.tribes[id].units++;result={icon:tribeData[id].icon,title:'魔物個体獲得',body:`${tribeData[id].name}の個体を1体獲得。`}}else{const eqPool=Object.entries(equipmentData).filter(([,e])=>rarityRank[e.rarity]<=rarityRank[rarity]);const [eid,e]=choice(eqPool);S.equipment[eid]=(S.equipment[eid]||0)+1;result={icon:e.icon,title:'装備獲得',body:`${e.name}を獲得。`}}S.gacha.history.unshift(`${result.icon} ${result.title}：${result.body.replace(/<[^>]*>/g,'')}`);S.gacha.history=S.gacha.history.slice(0,10);showResult(result.icon,result.title,result.body);renderAll()}
function renderGacha(){const used=S.gacha.dailyDate===today();dom.dailyBtn.disabled=used;dom.dailyBtn.textContent=used?'本日分受取済み':'無料で引く';dom.dailyBadge.textContent=used?'明日また引ける':'無料1回';const nr=currentRates('normal'),pr=currentRates('premium');dom.normalRates.textContent=Object.entries(nr).map(([k,v])=>`${k} ${v}%`).join(' / ');dom.premiumRates.textContent=Object.entries(pr).map(([k,v])=>`${k} ${v}%`).join(' / ');dom.normalPity.textContent=`天井 ${S.gacha.normalPity} / 50`;dom.premiumPity.textContent=`天井 ${S.gacha.premiumPity} / 30`;dom.history.innerHTML=S.gacha.history.length?S.gacha.history.map(x=>`<div class="history-item">${x}</div>`).join(''):'<div class="history-item">まだ召喚していない。</div>'}
function createMonsterStates(){monsterStates={};S.placed.forEach(p=>{const st=tribeStats(p.tribe);monsterStates[p.id]={hp:st.hp,max:st.hp,dead:false}})}
function createHero(){const learn=S.heroMemory.battles*.6+S.heroMemory.slimeDeaths*.5+S.heroMemory.bossReached*1.5;const max=30+(S.stage-1)*8+(S.wave-1)*6+Math.floor(learn);return{hp:max,maxHp:max,atk:6+Math.floor(S.stage*1.2)+Math.floor(learn/5),bossAtk:8+S.stage+S.wave+Math.floor(learn/6),cell:S.map.entrance,trait:S.heroMemory.slimeDeaths>=4?'対スライム剣':''}}
function damageFloat(cell,amount){const c=dom.grid.children[cell],e=document.createElement('span');e.className='damage';e.textContent=`-${amount}`;c.appendChild(e);setTimeout(()=>e.remove(),800)}
async function battleStart(){if(battle||!S.placed.length)return showToast(S.placed.length?'戦闘中':'まず魔物を配置しよう');battle=true;dom.battleBtn.disabled=true;createMonsterStates();hero=createHero();S.heroMemory.battles++;route=pathfind(S.map.entrance,S.map.goal,S.map.rocks)||[];for(let n=3;n>=1;n--){dom.battleLog.textContent=`勇者侵入まで ${n}…`;await wait(500)}for(const cell of route){hero.cell=cell;renderGrid();await wait(280);if(cell===S.map.goal){await bossFight();return}const p=S.placed.find(x=>x.cell===cell&&!monsterStates[x.id].dead);if(p){const heroWon=await monsterFight(p);if(!heroWon){await heroDefeated();return}}}}
async function monsterFight(p){const t=S.tribes[p.tribe],d=tribeData[p.tribe],st=monsterStates[p.id],stats=tribeStats(p.tribe);while(hero.hp>0&&st.hp>0){let hd=Math.max(1,hero.atk+rand(-2,2));if(hero.trait&&p.tribe==='slime')hd+=3;st.hp-=hd;damageFloat(p.cell,hd);renderGrid();await wait(420);if(st.hp<=0){st.dead=true;t.deaths++;const injured=Math.random()<.3;if(injured){t.injured++;dom.battleLog.textContent=`${d.name}は負傷し、治療待ちになった。`}else{dom.battleLog.textContent=`${d.name}の個体が死亡した。`}await wait(430);return true}let md=Math.max(1,stats.atk+rand(-1,2));if(p.tribe==='wolf'&&st.hp===st.max)md+=3;if(p.tribe==='undead'&&st.hp<1&&Math.random()<.25){st.hp=Math.ceil(st.max*.35);dom.battleLog.textContent='アンデッドが復活した！';renderGrid();continue}hero.hp-=md;damageFloat(p.cell,md);renderGrid();await wait(420);if(hero.hp<=0){hero.hp=0;t.kills++;t.xp+=10;while(t.xp>=t.proficiency*20){t.xp-=t.proficiency*20;t.proficiency++}return false}}return hero.hp>0}
async function heroDefeated(){const reward=45+S.stage*15+S.wave*12;S.gold+=reward;dom.battleLog.textContent=`勇者撃退！ +${reward}G`;dropLoot();await wait(600);await progressWave()}
async function bossFight(){S.heroMemory.bossReached++;while(hero.hp>0&&S.boss.hp>0){const d=Math.max(2,hero.bossAtk+rand(-2,3));S.boss.hp=Math.max(0,S.boss.hp-d);damageFloat(S.map.goal,d);renderAll();await wait(480);if(S.boss.hp<=0){const loss=Math.max(50,Math.floor(S.gold*.2));S.gold=Math.max(0,S.gold-loss);dom.battleLog.textContent=`魔王敗北…。${loss}G失った。`;S.wave=1;S.boss.hp=S.boss.maxHp;generateMap();finishBattle();return}const md=12+Math.floor(S.stage*1.5)+rand(-2,3);hero.hp-=md;damageFloat(S.map.goal,md);renderGrid();await wait(480)}if(hero.hp<=0){const reward=60+S.stage*18+S.wave*15;S.gold+=reward;dom.battleLog.textContent=`魔王が撃退！ +${reward}G`;dropLoot();await wait(600);await progressWave()}}
function dropLoot(){const r=Math.random();if(r<.28){const eqid=choice(Object.keys(equipmentData));S.equipment[eqid]=(S.equipment[eqid]||0)+1;S.records.equipmentDrops++;showToast(`${equipmentData[eqid].name}を拾った！`)}else if(r<.5){S.gems++;showToast('魔晶石を1個獲得！')}}
async function progressWave(){hero=null;if(S.wave>=WAVES){S.records.stageClears++;S.gold+=150+S.stage*70;S.stage++;newStage();finishBattle();return}S.wave++;S.boss.hp=Math.min(S.boss.maxHp,S.boss.hp+Math.max(3,Math.floor(S.boss.maxHp*.08)));finishBattle()}
function finishBattle(){battle=false;hero=null;monsterStates={};dom.battleBtn.disabled=false;renderAll();persistGame()}
function renderAll(){dom.gold.textContent=S.gold.toLocaleString();dom.gems.textContent=S.gems;dom.stage.textContent=S.stage;dom.wave.textContent=`${S.wave}/${WAVES}`;dom.bossText.textContent=`${S.boss.hp} / ${S.boss.maxHp}`;dom.bossFill.style.width=`${Math.max(0,S.boss.hp/S.boss.maxHp*100)}%`;dom.titleText.textContent=`第${S.stage}地下迷宮`;dom.battleBtn.querySelector('small').textContent=`STAGE ${S.stage}・WAVE ${S.wave}`;dom.routeInfo.textContent=`入口から魔王まで${route.length}マス。勇者は学習値に応じて強化される。`;createGrid();renderHand();renderGacha();renderEnhance();renderStatus();renderCodex();scheduleAutoSave()}
function switchPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$(`page${name}`).classList.add('active-page');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===name));window.scrollTo({top:0,behavior:'smooth'})}
function save(){if(battle)return showToast('戦闘終了後にセーブしてね');persistGame({silent:false});dom.menu.classList.add('hidden')}
function load(){restoreGame()}
function start(){S=freshState();dom.title.classList.add('hidden');dom.game.classList.remove('hidden');newStage();persistGame()}
function healInjured(){Object.values(S.tribes).forEach(t=>{if(t.injured>0){t.units+=t.injured;t.injured=0}})}
dom.newGame.onclick=start;dom.cont.onclick=load;dom.clear.onclick=clearPlaced;dom.battleBtn.onclick=battleStart;dom.dailyBtn.onclick=()=>doGacha('daily');dom.normalBtn.onclick=()=>doGacha('normal');dom.premiumBtn.onclick=()=>doGacha('premium');$('menuButton').onclick=()=>dom.menu.classList.remove('hidden');$('closeMenuButton').onclick=()=>dom.menu.classList.add('hidden');$('saveButton').onclick=save;$('titleButton').onclick=()=>{if(battle)return showToast('戦闘中は戻れない');dom.menu.classList.add('hidden');dom.game.classList.add('hidden');dom.title.classList.remove('hidden');persistGame()};$('closeResultButton').onclick=()=>dom.result.classList.add('hidden');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));dom.grid.addEventListener('pointermove',e=>{if(!pointerActive)return;const el=document.elementFromPoint(e.clientX,e.clientY)?.closest('.dungeon-cell');if(el)processCell(Number(el.dataset.i))});window.addEventListener('pointerup',pointerEnd);window.addEventListener('pointercancel',pointerEnd);window.addEventListener('pagehide',()=>persistGame());window.addEventListener('beforeunload',()=>persistGame());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persistGame()});if(!restoreGame()){generateMap();renderAll()}setInterval(()=>{healInjured();renderAll();persistGame()},600000);
