(()=>{'use strict';
const KEY='abyssDominion_alpha_v07',TILE=54,MW=21,MH=21;
const DEF={floor:1,maxFloor:1,gold:0,inRun:false,maxHp:160,hp:160,skillPower:1,atkBoost:0,skillBoost:0,upgrades:{atk:0,hp:0,skill:0}};
const PARTY={slime:{name:'スライム',color:'#42d66a',hp:42,atk:6,interval:1,crit:.08,skills:[['粘液体当たり',1.2],['分裂突進',1.6]]},goblin:{name:'ゴブリン',color:'#918353',hp:50,atk:9,interval:.78,crit:.16,skills:[['二連斬り',1.5],['急所突き',2]]},fairy:{name:'妖精',color:'#7fe3f7',hp:32,atk:3,interval:1.45,crit:.05,healer:true,skills:[['単体回復',0],['全体回復',0]]},dragon:{name:'ドラゴン',color:'#da5656',hp:125,atk:30,interval:5.4,crit:.2,skills:[['火炎ブレス',2.2],['竜爪撃',1.7]]}};
const TYPES=[{name:'洞窟スライム',color:'#58c96e',base:1},{name:'岩ゴブリン',color:'#9a8455',base:1.15},{name:'毒キノコ',color:'#b060ca',base:1.25},{name:'子ワイバーン',color:'#c35b5b',base:1.55}];
let state=load(),game=null,raf=0,last=0;const $=id=>document.getElementById(id),canvas=$('gameCanvas'),ctx=canvas.getContext('2d'),screens=['homeScreen','gameScreen','rewardScreen','resultScreen'];
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{return Object.assign(clone(DEF),JSON.parse(localStorage.getItem(KEY))||{})}catch{return clone(DEF)}}function save(){localStorage.setItem(KEY,JSON.stringify(state))}function show(id){screens.forEach(x=>$(x).classList.toggle('active',x===id))}function toast(t,ms=900){const e=$('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),ms)}
function sync(){$('floorText').textContent=state.floor;$('goldText').textContent=Math.floor(state.gold);$('armyHpText').textContent=`${Math.max(0,Math.ceil(state.hp))}/${state.maxHp}`;$('armyHpBar').style.width=`${Math.max(0,state.hp/state.maxHp*100)}%`;$('boostText').textContent=`ATK +${Math.round(state.atkBoost*100)}%　SKILL +${Math.round(state.skillBoost*100)}%`}
function dungeon(){const g=Array.from({length:MH},()=>Array(MW).fill(1));function carve(x,y){g[y][x]=0;for(const [dx,dy] of [[2,0],[-2,0],[0,2],[0,-2]].sort(()=>Math.random()-.5)){const nx=x+dx,ny=y+dy;if(nx>0&&ny>0&&nx<MW-1&&ny<MH-1&&g[ny][nx]===1){g[y+dy/2][x+dx/2]=0;carve(nx,ny)}}}carve(1,1);for(let i=0;i<25;i++){const x=1+Math.floor(Math.random()*(MW-2)),y=1+Math.floor(Math.random()*(MH-2));if(g[y][x]===1&&((g[y][x-1]===0&&g[y][x+1]===0)||(g[y-1][x]===0&&g[y+1][x]===0)))g[y][x]=0}return g}
function cells(g){const a=[];for(let y=1;y<MH-1;y++)for(let x=1;x<MW-1;x++)if(g[y][x]===0)a.push({x,y});return a}function dist(a,b){return Math.abs(a.x-b.x)+Math.abs(a.y-b.y)}function pick(a,from,min,ex=[]){const b=a.filter(c=>dist(c,from)>=min&&!ex.some(e=>e.x===c.x&&e.y===c.y));return clone(b[Math.floor(Math.random()*b.length)]||a[a.length-1])}
function bfs(g,s,t){const key=p=>`${p.x},${p.y}`,q=[s],seen=new Set([key(s)]),prev=new Map(),ds=[[1,0],[-1,0],[0,1],[0,-1]];while(q.length){const c=q.shift();if(c.x===t.x&&c.y===t.y)break;for(const [dx,dy] of ds){const n={x:c.x+dx,y:c.y+dy},k=key(n);if(n.x<0||n.y<0||n.x>=MW||n.y>=MH||g[n.y][n.x]===1||seen.has(k))continue;seen.add(k);prev.set(k,c);q.push(n)}}const p=[];let c=t;while(c&&!(c.x===s.x&&c.y===s.y)){p.push(c);c=prev.get(key(c))}p.push(s);return p.reverse()}
function makeParty(){return Object.entries(PARTY).map(([id,d],i)=>({id,name:d.name,color:d.color,maxHp:d.hp,hp:d.hp,atk:d.atk*(1+state.atkBoost)+state.upgrades.atk*1.5,interval:d.interval,crit:d.crit,healer:!!d.healer,skills:d.skills,cd:Math.random()*d.interval,damage:0,healing:0,alive:true,x:145+(i%2)*75,y:470+Math.floor(i/2)*80,guard:false}))}
function spawn(force=false){if(!game||game.phase!=='explore')return;const living=game.enemies.filter(e=>e.alive).length;if(!force&&living>=game.cap)return;const c=game.open.filter(p=>dist(p,game.player)>=8&&dist(p,game.exit)>=3&&dist(p,{x:1,y:1})>=4&&!game.enemies.some(e=>e.alive&&e.x===p.x&&e.y===p.y));if(!c.length)return;const p=clone(c[Math.floor(Math.random()*c.length)]),t=TYPES[Math.min(TYPES.length-1,Math.floor(Math.random()*Math.min(TYPES.length,1+state.floor/15)))],lv=Math.max(1,state.floor+Math.floor(Math.random()*7)-2);game.enemies.push({id:Date.now()+Math.random(),x:p.x,y:p.y,px:p.x,py:p.y,path:[],moveT:0,alive:true,patrol:1+Math.random()*2,type:t,level:lv,alert:0})}
function startRun(){state.inRun=true;state.floor=Math.max(1,state.maxFloor);state.maxHp=160+state.upgrades.hp*20;state.hp=state.maxHp;state.skillPower=1+state.upgrades.skill*.12;save();setup()}
function setup(){const map=dungeon(),open=cells(map),start={x:1,y:1},exit=pick(open,start,14,[start]),ch=[pick(open,start,7,[start,exit]),pick(open,start,5,[start,exit])];game={phase:'explore',paused:false,map,open,player:{x:1,y:1,px:1,py:1,path:[],moveT:0},camera:{x:TILE,y:TILE},exit,chests:ch.map(p=>({...p,opened:false})),enemies:[],party:makeParty(),battleEnemy:null,particles:[],floats:[],shake:0,auto:true,activeIndex:0,cap:Math.min(10,4+Math.floor(state.floor/80)),spawnTimer:8,lastSummary:null,rewardShown:false,zoom:1,pinch:{},items:{potion:3}};for(let i=0;i<game.cap;i++)spawn(true);show('gameScreen');$('battleUi').classList.add('hidden');last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);sync();save()}
function mover(o,dt,s=4){if(!o.path.length)return false;const t=o.path[0];o.moveT+=dt*s;o.px=o.x+(t.x-o.x)*Math.min(1,o.moveT);o.py=o.y+(t.y-o.y)*Math.min(1,o.moveT);if(o.moveT>=1){o.x=t.x;o.y=t.y;o.px=o.x;o.py=o.y;o.path.shift();o.moveT=0;return true}return false}
function tileFromEvent(e){const r=canvas.getBoundingClientRect(),sx=(e.clientX-r.left)*(720/r.width),sy=(e.clientY-r.top)*(980/r.height);return{x:Math.floor((sx-360)/(TILE*game.zoom)+game.camera.x/TILE),y:Math.floor((sy-490)/(TILE*game.zoom)+game.camera.y/TILE)}}
function playerStep(){for(const c of game.chests)if(!c.opened&&c.x===game.player.x&&c.y===game.player.y){c.opened=true;const g=40+state.floor*3;state.gold+=g;toast(`宝箱！ +${g}G`)}for(const e of game.enemies)if(e.alive&&e.x===game.player.x&&e.y===game.player.y){battle(e);return}if(game.player.x===game.exit.x&&game.player.y===game.exit.y){cancelAnimationFrame(raf);rewardsScreen()}}
function enemiesUpdate(dt){for(const e of game.enemies){if(!e.alive)continue;e.patrol-=dt;const d=dist(e,game.player);if(d<=4){e.alert=1;e.path=bfs(game.map,{x:e.x,y:e.y},{x:game.player.x,y:game.player.y}).slice(1)}else{e.alert=Math.max(0,e.alert-dt);if(e.patrol<=0&&!e.path.length){const n=[[1,0],[-1,0],[0,1],[0,-1]].map(([dx,dy])=>({x:e.x+dx,y:e.y+dy})).filter(p=>game.map[p.y]&&game.map[p.y][p.x]===0);if(n.length)e.path=[n[Math.floor(Math.random()*n.length)]];e.patrol=1.2+Math.random()*2}}if(mover(e,dt,e.alert?4.3:2.1)&&e.x===game.player.x&&e.y===game.player.y){battle(e);return}}
if(Math.random()<dt*.015){const a=game.enemies.filter(e=>e.alive);if(a.length>=2){const x=a[Math.floor(Math.random()*a.length)],y=a[Math.floor(Math.random()*a.length)];if(x!==y&&dist(x,y)<=1)toast(`${x.type.name}と${y.type.name}が睨み合っている…`,1200)}}}
function stats(e){const hp=Math.round((65+e.level*7)*e.type.base);return{name:e.type.name,level:e.level,hp,maxHp:hp,atk:Math.round((5+e.level*.5)*e.type.base),cd:1}}
function battle(e){game.phase='battle';game.player.path=[];e.path=[];game.battleEnemy=e;e.battle=stats(e);game.party=makeParty();game.activeIndex=0;$('battleUi').classList.remove('hidden');toast(`${e.type.name} Lv.${e.level} と遭遇！`);commands()}
function active(){return game.party[game.activeIndex]}function next(){game.activeIndex=(game.activeIndex+1)%game.party.length;for(let i=0;i<game.party.length;i++){const m=active();if(m.alive)return m;game.activeIndex=(game.activeIndex+1)%game.party.length}return null}
function autoCmd(m){if(m.healer){const low=[...game.party].filter(x=>x.alive).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(low&&low.hp/low.maxHp<.55)return{kind:'skill',index:low.hp/low.maxHp<.25?1:0}}if(m.hp/m.maxHp<.22)return{kind:'guard'};if(game.items.potion>0&&m.hp/m.maxHp<.18)return{kind:'item'};if(Math.random()<.45)return{kind:'skill',index:Math.random()<.5?0:1};return{kind:'attack'}}
function command(c){const m=active();if(!m||!m.alive)return;if(c.kind==='attack')attack(m,1,'通常攻撃');if(c.kind==='guard'){m.guard=true;toast(`${m.name}はガード`)}if(c.kind==='item'&&game.items.potion>0){game.items.potion--;const h=30;m.hp=Math.min(m.maxHp,m.hp+h);float(`+${h}`,m.x,m.y-45,'#8dff9c',26)}if(c.kind==='skill'){if(m.healer){const alive=game.party.filter(x=>x.alive);if(c.index===0){const t=[...alive].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],h=Math.round(22*state.skillPower*(1+state.skillBoost));t.hp=Math.min(t.maxHp,t.hp+h);m.healing+=h;float(`+${h}`,t.x,t.y-45,'#8dff9c',28)}else for(const t of alive){const h=Math.round(12*state.skillPower*(1+state.skillBoost));t.hp=Math.min(t.maxHp,t.hp+h);m.healing+=h;float(`+${h}`,t.x,t.y-45,'#8dff9c',24)}}else attack(m,m.skills[c.index][1],m.skills[c.index][0])}next();commands()}
function attack(m,p,label){const b=game.battleEnemy.battle,base=Math.max(1,Math.round(m.atk*p*(.85+Math.random()*.3))),crit=Math.random()<m.crit,d=crit?Math.round(base*1.8):base;b.hp-=d;m.damage+=d;float(crit?`CRIT ${d}`:`-${d}`,525,430-Math.random()*40,crit?'#fff2a8':'#ffd76a',crit?35:29);burst(525,510,crit?'#fff1a4':'#ff9c54',crit?25:12);game.shake=crit?11:4;toast(`${m.name}：${label}`,450)}
function enemyAct(){const alive=game.party.filter(x=>x.alive);if(!alive.length){state.hp-=game.battleEnemy.battle.atk;return}const t=[...alive].sort((a,b)=>a.hp-b.hp)[0],d=Math.max(1,Math.round(game.battleEnemy.battle.atk*(t.guard?.5:1)));t.guard=false;t.hp-=d;float(`-${d}`,t.x,t.y-42,'#ff7777',25);if(t.hp<=0)t.alive=false}
function battleUpdate(dt){const b=game.battleEnemy.battle;b.cd-=dt;if(game.auto){const m=active();m.cd-=dt;if(m.cd<=0){m.cd=m.interval;command(autoCmd(m))}}if(b.cd<=0){b.cd=1.15;enemyAct()}if(b.hp<=0){game.battleEnemy.alive=false;game.lastSummary=game.party.map(m=>({name:m.name,damage:Math.round(m.damage),healing:Math.round(m.healing)}));game.phase='explore';game.battleEnemy=null;$('battleUi').classList.add('hidden');state.gold+=20;toast('勝利！');game.spawnTimer=Math.min(game.spawnTimer,4)}if(state.hp<=0){cancelAnimationFrame(raf);const lost=Math.floor(state.gold*.5);state.gold-=lost;state.inRun=false;result('DEFEAT','敗北',[`失ったG：${lost}`])}}
function commands(){const m=active();$('turnLabel').textContent=m?`${m.name}の行動`:'行動待ち';$('autoBtn').textContent=game.auto?'AUTO ON':'MANUAL';$('commandRoot').style.opacity=game.auto?.55:1;$('subCommands').innerHTML=''}
function burst(x,y,color,count=14){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*170;game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.4+Math.random()*.4,max:.8,size:3+Math.random()*6,color})}}function float(text,x,y,color,size){game.floats.push({text,x,y,vy:-55,life:1,max:1,color,size})}
function update(dt){if(game.paused)return;if(game.phase==='explore'){if(mover(game.player,dt,4.8))playerStep();enemiesUpdate(dt);game.spawnTimer-=dt;if(game.spawnTimer<=0){spawn();game.spawnTimer=12+Math.random()*12}game.camera.x+=(game.player.px*TILE-game.camera.x)*Math.min(1,dt*6);game.camera.y+=(game.player.py*TILE-game.camera.y)*Math.min(1,dt*6)}else battleUpdate(dt);for(const p of game.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt}game.particles=game.particles.filter(p=>p.life>0);for(const f of game.floats){f.life-=dt;f.y+=f.vy*dt}game.floats=game.floats.filter(f=>f.life>0);game.shake=Math.max(0,game.shake-dt*18);sync();save()}
function rr(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}function bar(x,y,w,h,v,max,color){rr(x,y,w,h,h/2,'#09070c','#4a3556');rr(x,y,Math.max(0,w*(v/max)),h,h/2,color,null)}
function draw(){ctx.save();ctx.translate(game.shake?(Math.random()-.5)*game.shake:0,game.shake?(Math.random()-.5)*game.shake:0);ctx.fillStyle='#09050d';ctx.fillRect(0,0,720,980);ctx.save();ctx.translate(360-game.camera.x*game.zoom,490-game.camera.y*game.zoom);ctx.scale(game.zoom,game.zoom);for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){ctx.fillStyle=game.map[y][x]?'#20152a':'#3a2947';ctx.fillRect(x*TILE,y*TILE,TILE,TILE);if(!game.map[y][x]){ctx.strokeStyle='rgba(255,255,255,.05)';ctx.strokeRect(x*TILE,y*TILE,TILE,TILE)}}for(const c of game.chests)if(!c.opened){ctx.font='30px sans-serif';ctx.fillText('🎁',c.x*TILE+12,c.y*TILE+38)}ctx.font='30px sans-serif';ctx.fillText('🪜',game.exit.x*TILE+12,game.exit.y*TILE+38);for(const e of game.enemies)if(e.alive){ctx.fillStyle=e.type.color;ctx.beginPath();ctx.arc(e.px*TILE+TILE/2,e.py*TILE+TILE/2,15,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.fillText(`Lv.${e.level}`,e.px*TILE+5,e.py*TILE+12)}ctx.fillStyle='#42d66a';ctx.beginPath();ctx.arc(game.player.px*TILE+TILE/2,game.player.py*TILE+TILE/2,17,0,Math.PI*2);ctx.fill();ctx.restore();mini();if(game.phase==='battle')battleDraw();for(const p of game.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const f of game.floats){ctx.globalAlpha=f.life/f.max;ctx.fillStyle=f.color;ctx.font=`900 ${f.size}px sans-serif`;ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.textAlign='start';ctx.restore()}
function mini(){const ox=555,oy=18,s=7;rr(ox-8,oy-8,160,160,12,'rgba(7,4,10,.8)','#4b355a');for(let y=0;y<MH;y++)for(let x=0;x<MW;x++){ctx.fillStyle=game.map[y][x]?'#21172a':'#8a62ac';ctx.fillRect(ox+x*s,oy+y*s,s-1,s-1)}ctx.fillStyle='#57ff8a';ctx.fillRect(ox+game.player.x*s+1,oy+game.player.y*s+1,5,5);for(const c of game.chests)if(!c.opened){ctx.fillStyle='#ffd65e';ctx.fillRect(ox+c.x*s+1,oy+c.y*s+1,5,5)}ctx.fillStyle='#ff5252';ctx.fillRect(ox+game.exit.x*s+1,oy+game.exit.y*s+1,5,5)}
function battleDraw(){ctx.fillStyle='rgba(7,4,10,.88)';ctx.fillRect(0,190,720,790);const b=game.battleEnemy.battle;ctx.fillStyle='#f3c76f';ctx.font='900 25px sans-serif';ctx.fillText(`${b.name} Lv.${game.battleEnemy.level}`,28,235);bar(28,252,664,18,b.hp,b.maxHp,'#e45f66');for(const m of game.party){ctx.fillStyle=m.color;ctx.beginPath();ctx.arc(m.x,m.y,19,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='11px sans-serif';ctx.fillText(m.name,m.x-28,m.y+34);bar(m.x-30,m.y+42,60,7,m.hp,m.maxHp,'#6bd27b')}ctx.fillStyle=game.battleEnemy.type.color;ctx.beginPath();ctx.arc(525,500,32,0,Math.PI*2);ctx.fill()}
function loop(ts){const dt=Math.min(.05,(ts-last)/1000||0);last=ts;update(dt);if(!game)return;draw();raf=requestAnimationFrame(loop)}
function rewardList(){return[{c:'red',t:'攻撃微増',d:'各魔物 ATK +2%',fn:()=>state.atkBoost+=.02,detail:'全魔物 ATK +2%'},{c:'blue',t:'魔力回復',d:'魔王軍HPを20%回復',fn:()=>state.hp=Math.min(state.maxHp,state.hp+state.maxHp*.2),detail:`魔王軍HP +${Math.round(state.maxHp*.2)}`},{c:'purple',t:'スキル微増',d:'スキル効果 +3%',fn:()=>state.skillBoost+=.03,detail:'全スキル効果 +3%'},{c:'gold',t:'ゴールド',d:`${50+state.floor*4}G`,fn:()=>state.gold+=50+state.floor*4,detail:`${50+state.floor*4}G獲得`}].sort(()=>Math.random()-.5).slice(0,3)}
function rewardsScreen(){if(game.rewardShown)return;game.rewardShown=true;const s=game.lastSummary||[],m=[...s].sort((a,b)=>(b.damage+b.healing)-(a.damage+a.healing))[0];$('battleSummary').innerHTML=`<div class="summaryCard">${s.map(x=>`<p>${x.name}: ${x.damage}ダメージ / ${x.healing}回復</p>`).join('')}<b>MVP: ${m?m.name:'—'}</b></div>`;const r=rewardList();$('rewardChoices').innerHTML=r.map((x,i)=>`<button class="rewardCard ${x.c}" data-r="${i}"><b>${x.t}</b><span>${x.d}</span></button>`).join('');let lock=false;$('rewardChoices').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{if(lock)return;lock=true;r[i].fn();alert(`${r[i].t}\n\n${r[i].detail}`);state.floor++;state.maxFloor=Math.max(state.maxFloor,state.floor);save();confirm('次の階へ進む？\nキャンセルで帰還。')?setup():safeReturn()});show('rewardScreen')}
function safeReturn(){cancelAnimationFrame(raf);state.inRun=false;save();result('SAFE RETURN','帰還成功',[`到達階: ${state.floor}`,`GOLD: ${state.gold}`])}function result(e,t,a){$('resultEye').textContent=e;$('resultTitle').textContent=t;$('resultBody').innerHTML=`<ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`;show('resultScreen')}
function renderHome(){const l=[['atk','軍団攻撃',state.upgrades.atk,100+state.upgrades.atk*120],['hp','最大HP',state.upgrades.hp,100+state.upgrades.hp*120],['skill','スキル威力',state.upgrades.skill,150+state.upgrades.skill*150]];$('upgradeList').innerHTML=l.map(([id,n,v,c])=>`<div class="upgradeRow"><span>${n} Lv.${v}</span><button data-up="${id}" data-cost="${c}">${c}G</button></div>`).join('')}
canvas.addEventListener('pointerdown',e=>{if(!game||game.phase!=='explore')return;canvas.setPointerCapture(e.pointerId);game.pinch[e.pointerId]={x:e.clientX,y:e.clientY};if(Object.keys(game.pinch).length===1){const t=tileFromEvent(e);if(game.map[t.y]&&game.map[t.y][t.x]===0)game.player.path=bfs(game.map,{x:game.player.x,y:game.player.y},t).slice(1)}});canvas.addEventListener('pointermove',e=>{if(!game||!game.pinch[e.pointerId])return;game.pinch[e.pointerId]={x:e.clientX,y:e.clientY};const p=Object.values(game.pinch);if(p.length===2){const d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(game.lastPinch)game.zoom=Math.max(.45,Math.min(1.35,game.zoom*d/game.lastPinch));game.lastPinch=d}});canvas.addEventListener('pointerup',e=>{if(game?.pinch){delete game.pinch[e.pointerId];if(Object.keys(game.pinch).length<2)game.lastPinch=null}});
$('startBtn').onclick=startRun;$('pauseBtn').onclick=()=>{if(game)game.paused=!game.paused};$('centerBtn').onclick=()=>{if(game){game.camera.x=game.player.px*TILE;game.camera.y=game.player.py*TILE;game.zoom=1}};$('returnBtn').onclick=()=>{if(confirm('帰還する？'))safeReturn()};$('homeBtn').onclick=()=>{game=null;renderHome();show('homeScreen')};$('autoBtn').onclick=()=>{game.auto=!game.auto;commands()};document.querySelector('.mainCommands').onclick=e=>{const b=e.target.closest('[data-main]');if(!b||game.auto)return;const m=b.dataset.main;if(m==='attack')command({kind:'attack'});if(m==='guard')command({kind:'guard'});if(m==='item')command({kind:'item'});if(m==='skills'){$('subCommands').innerHTML=active().skills.map((s,i)=>`<button data-skillidx="${i}">${s[0]}</button>`).join('')}};$('subCommands').onclick=e=>{const b=e.target.closest('[data-skillidx]');if(b&&!game.auto)command({kind:'skill',index:+b.dataset.skillidx})};$('upgradeList').onclick=e=>{const b=e.target.closest('[data-up]');if(!b)return;const c=+b.dataset.cost,id=b.dataset.up;if(state.gold<c)return alert('G不足');state.gold-=c;state.upgrades[id]++;save();renderHome()};
renderHome();sync();if(state.inRun)setup();else show('homeScreen');})();
